### ISSUE TITLE
Plugin does not compile on Unity 6.5: GetInstanceID family is now a hard error

### ISSUE THREAD

**Issue by DarkMasster** [german-krasnikov/unity-biome-mcp#52]
**Base:** `master` @ 329dd0f (2026-08-18) — the patch applies cleanly there.
`TransientObjectId.cs` on master still calls `GetInstanceID()`,
`EditorUtility.InstanceIDToObject` and `objectReferenceInstanceIDValue`, so the package
still does not compile on Unity 6.5.
**Verified on:** v1.39.0 in a live project (compile + tests, details at the end).
**Unity:** 6000.5.3f1
**Package:** `com.unity-biome-mcp.editor`

## What happens

The editor assembly fails to compile, so the plugin never loads and the MCP bridge
never comes up. The first three CS0619 errors are all in `Editor/TransientObjectId.cs`:

```
Editor/TransientObjectId.cs(29,65): error CS0619: 'Object.GetInstanceID()' is obsolete:
  'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
Editor/TransientObjectId.cs(83,20): error CS0619: 'EditorUtility.InstanceIDToObject(int)' is obsolete:
  'InstanceIDToObject(int) is obsolete. Use EditorUtility.EntityIdToObject instead.'
Editor/TransientObjectId.cs(91,20): error CS0619: 'SerializedProperty.objectReferenceInstanceIDValue' is obsolete:
  'objectReferenceInstanceIDValue is obsolete. Use objectReferenceEntityIdValue instead'
```

Unity reports one failing assembly at a time, so fixing those uncovers the rest.
The same instance-id API is reached in four more places:

- `Editor/Chat/View/MCPChatWindow.TestIsolation.cs` — two call sites plus a
  `Dictionary<int, MCPChatWindow>` keyed by instance id
- `Editor/TestSupport/UnityMcpTestBase.cs` — two call sites plus a `HashSet<int>`
- `Editor/Tests/TestRunIsolationSafetyTests.cs` — two call sites
- `Editor/Tests/TransientObjectIdTests.cs` — one call site

And once `UnityMCP.Editor.Chat.CLI` gets its turn, a second deprecation joins in:

```
Editor/Chat/CLI/SceneHeaderContextMenu.cs(18,16): error CS0619:
  'EditorApplication.hierarchyWindowItemOnGUI' is obsolete:
  'hierarchyWindowItemOnGUI is obsolete. Use hierarchyWindowItemByEntityIdOnGUI instead.'
```

`CS0619` comes from `[Obsolete(..., error: true)]`, so it cannot be suppressed with
`#pragma warning disable` or `-nowarn`. There is no workaround on the consumer side —
the package simply cannot be used on Unity 6.5.

## Background

Unity 6.4 deprecated the instance-id API in favour of the `EntityId` struct and emitted
warnings; Unity 6.5 turned those warnings into errors. `package.json` declares
`"unity": "6000.0"`, which is still accurate for 6.0–6.3, so the fix needs to keep both
paths alive rather than replace one with the other.

## Suggested fix

A small compatibility layer in the core assembly, guarded by `UNITY_6000_4_OR_NEWER`,
plus call sites updated to use it. Patch attached (`biome-mcp-entityid-unity65.patch`,
`git apply` from the repository root, 9 files).

Three details worth keeping in mind:

1. **Do not cast `EntityId` to or from an integer.** Unity's own documentation says the
   bit layout and sign conventions are not part of the contract, and that
   `EntityId.ToULong()` / `EntityId.FromULong()` are the sanctioned round-trip (both are
   static methods taking the id, not instance methods). That fits `TransientObjectId`
   well — it already stores a `ulong` — and it removes the existing
   `unchecked((int)RawValue)` truncation in `Resolve()`, which does assume a layout.
   On 6000.5.3f1 a fresh `GameObject` reports `568105589213679802`, so that truncation
   is not theoretical: the id no longer fits 32 bits.
2. **Identity keys become `ulong`.** Dictionaries and sets currently keyed by `int`
   instance ids change to `ulong`. The wire format is unaffected: `WireValue` and
   `HexRef` already serialise the `ulong`, and the legacy sign-extended parse branch
   in `TryParse` is left untouched so old references still resolve.
3. **`SceneHeaderContextMenu` needs more than a renamed event.** Its row ids are scene
   handles, not object ids, and `Scene.handle` is now a `SceneHandle` struct whose
   implicit conversion to `int` is also a hard error. Measured on 6000.5.3f1: the
   Hierarchy hands the header row an `EntityId` whose `ToULong()` is exactly
   `scene.handle.GetRawData()` (`568105589213684528` for the open scene), while the old
   comparison key `Scene.GetHashCode()` is `-72912`. So the row id has to stay 64 bits
   wide and be compared through `SceneHandle.FromRawData`; truncating it to `int` keeps
   compiling and silently stops matching any scene.

The new helper is `Editor/ObjectIdCompat.cs`:

```csharp
public static class ObjectIdCompat
{
    public static ulong StableKey(Object value)
    {
#if UNITY_6000_4_OR_NEWER
        return EntityId.ToULong(value.GetEntityId());
#else
        return unchecked((ulong)(long)value.GetInstanceID());
#endif
    }

    public static Object Resolve(ulong key)
    {
#if UNITY_6000_4_OR_NEWER
        return EditorUtility.EntityIdToObject(EntityId.FromULong(key));
#else
        return EditorUtility.InstanceIDToObject(unchecked((int)key));
#endif
    }

    public static void AddHierarchyItemGui(Action<ulong, Rect> handler)
    {
#if UNITY_6000_4_OR_NEWER
        EditorApplication.hierarchyWindowItemByEntityIdOnGUI +=
            (entityId, selectionRect) => handler(EntityId.ToULong(entityId), selectionRect);
#else
        EditorApplication.hierarchyWindowItemOnGUI +=
            (instanceId, selectionRect) =>
                handler(unchecked((ulong)(long)instanceId), selectionRect);
#endif
    }

    public static bool IsSceneRow(ulong rowId, Scene scene)
    {
#if UNITY_6000_4_OR_NEWER
        return scene.handle.Equals(SceneHandle.FromRawData(rowId));
#else
        return scene.GetHashCode() == unchecked((int)rowId);
#endif
    }

    public static bool HasSerializedReference(SerializedProperty property)
    {
#if UNITY_6000_4_OR_NEWER
        return property.objectReferenceEntityIdValue != EntityId.None;
#else
        return property.objectReferenceInstanceIDValue != 0;
#endif
    }
}
```

It is `public` rather than `internal` on purpose: `UnityMCP.Editor.Chat.View`,
`UnityMCP.Editor.Chat.CLI`, `UnityMCP.Editor.TestSupport` and the test assemblies are
separate asmdefs and cannot see internals of `UnityMCP.Editor`.

`SceneHeaderContextMenu.ScenePathFinder`, `OnHierarchyItemGUI` and `FindScenePath` change
their parameter from `int` to `ulong`, and the four literals in
`SceneHeaderContextMenuTests` change with them (`-999999` becomes `999999UL`, since a
negative row id is no longer representable).

## What is verified and what is not

Verified on 6000.5.3f1 with the patch applied:

- the package compiles with zero errors, the plugin loads and the MCP bridge comes up;
- `EditorUtility.EntityIdToObject(EntityId.FromULong(EntityId.ToULong(id)))` returns the
  same object instance it started from, so `StableKey` / `Resolve` round-trip;
- the scene-header path lookup still works: feeding `FindScenePath` the raw row id that
  the Hierarchy actually produced returns `Assets/Scenes/StartScene.unity`, and a
  neighbouring id returns `null`.

- the tests that cover the touched code pass: `SceneHeaderContextMenuTests` 4/4 and
  `TransientObjectIdTests` 19/19, the latter including the legacy signed-token and
  unsigned-wire-precision cases that guard the `int` → `ulong` change.

Not verified: behaviour on Unity 6.0–6.3 (the `#else` branches are the original code
unchanged, but they have not been compiled on those versions here), and the full plugin
suite — only the fixtures above were run.

Side note in case it saves you time: getting to those test runs at all needed two
unrelated fixes in `DiagnoseCommand`, without which `run_tests` answers
`BLOCKED: FAIL:unknown` on any clean project. They are described in a separate report
with their own patch, and do not overlap this one by file.

The code was written and verified against v1.39.0, then rebased onto master; the rebase
was textual and needed no conflict resolution in these files.

## Patch

[`biome-mcp-entityid-unity65.patch`](https://gist.github.com/DarkMasster/e1cc4b593bd4602dac6c23c703dc68bc) — 9 files, applies to `master` @ 329dd0f:

```
curl -L https://gist.github.com/DarkMasster/e1cc4b593bd4602dac6c23c703dc68bc/raw/biome-mcp-entityid-unity65.patch | git apply
```

`git apply --check` passes on a clean master worktree.

**Comment by german-krasnikov** [comment]
Hey! Thank you so much for this incredibly detailed bug report — the exact error messages, the verified patch, the `ObjectIdCompat` design with `EntityId.ToULong()`/`EntityId.FromULong()` round-trip, and the call-site inventory made this a pleasure to work on. Reports like this are rare and deeply appreciated. 🙌

**Fixed in [v1.44.0](https://github.com/german-krasnikov/unity-biome-mcp/releases/tag/v1.44.0)** via PR #56.

### What was done

- **`ObjectIdCompat.cs`** — static compat layer with `#if UNITY_6000_4_OR_NEWER` guards, exactly as you proposed: `GetRawId()`, `ResolveObject()`, `HasSerializedReference()` bridging at `ulong`
- **`SceneHeaderContextMenu.cs`** — two handler methods under `#if` for the delegate signature change (`hierarchyWindowItemByEntityIdOnGUI`)
- **Test infrastructure** — migrated to reference equality (`HashSet<EditorWindow>`) instead of int-keyed collections — zero `#if` needed
- **`Scene.handle`** — all 14 identity comparisons replaced with `==` operator
- **`HexRef`** — expanded to full 64-bit hex to prevent silent collisions with large EntityIds
- **`ObjectIdCompatTests.cs`** — round-trip, presence, and type-guard tests

### CI coverage

Tests now run on **7 Unity versions in parallel** (6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.7 Alpha) via the new `unity-compat.yml` workflow. The `#if` branch compiles and passes on 6.4+; the `#else` branch verified on 6.0 baseline.

Closing this as resolved. If anything regresses on a specific Unity version, feel free to reopen!
